# Generated by Django 5.2.11 on 2026-03-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_brand_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('watt', models.CharField(blank=True, help_text='Quvvat (masalan: 20W)', max_length=20)),
                ('voltage', models.CharField(blank=True, help_text='Kuchlanish (masalan: 3.7V)', max_length=20)),
                ('capacity', models.CharField(blank=True, help_text="Sig'im (masalan: 5000mAh)", max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand')),
            ],
            options={
                'verbose_name_plural': 'Batteries',
                'db_table': 'batteries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('watt', models.CharField(blank=True, help_text='Quvvat (masalan: 65W)', max_length=20)),
                ('voltage', models.CharField(blank=True, help_text='Kuchlanish (masalan: 12V)', max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand')),
            ],
            options={
                'db_table': 'chargers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('hz', models.CharField(blank=True, help_text='Chastota (masalan: 60Hz, 144Hz)', max_length=20)),
                ('pin', models.CharField(blank=True, help_text='Pin (masalan: 30pin, 40pin)', max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand')),
            ],
            options={
                'db_table': 'displays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
