# Generated by Django 5.2.11 on 2026-03-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category_remove_product_brand_battery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charger',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='display',
            name='model_name',
        ),
    ]
