# Generated by Django 5.2.11 on 2026-03-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_battery_created_at_alter_battery_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='charger',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='watt',
        ),
        migrations.RemoveField(
            model_name='charger',
            name='voltage',
        ),
        migrations.AlterField(
            model_name='battery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
