# Generated by Django 5.2.11 on 2026-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_display_brand_remove_battery_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='voltage',
        ),
        migrations.AddField(
            model_name='charger',
            name='voltage',
            field=models.CharField(blank=True, help_text='Kuchlanish (masalan: 19V, 20V)', max_length=20),
        ),
    ]
