# Generated by Django 5.2.11 on 2026-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_battery_voltage_charger_voltage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='model_name',
        ),
        migrations.AddField(
            model_name='battery',
            name='category',
            field=models.CharField(blank=True, help_text='Brand (masalan: HP, Asus, Acer)', max_length=100),
        ),
        migrations.AddField(
            model_name='charger',
            name='category',
            field=models.CharField(blank=True, help_text='Brand (masalan: HP, Asus, Acer)', max_length=100),
        ),
    ]
